source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HaidoraPaging_Example', :exclusive => true do
  pod "HaidoraPaging", :path => "../"
end

target 'HaidoraPaging_Tests', :exclusive => true do
  pod "HaidoraPaging", :path => "../"

  
end
